import React from 'react';
import {Audio} from '@remotion/media';
import {staticFile, useVideoConfig} from 'remotion';
import type {Lang} from '../lang';

/**
 * The score + sound design are generated by scripts/generate-audio.mjs from the same cue table
 * the scenes animate from (src/timing.ts), then mixed to one stereo file per language.
 * The film also plays fine muted: it is text-led.
 */
export const FilmAudio: React.FC<{lang: Lang}> = ({lang}) => {
  const {durationInFrames} = useVideoConfig();
  return <Audio src={staticFile(`audio/mix-${lang}.mp3`)} trimAfter={durationInFrames} />;
};
